import type { TagSchemaField } from "@/lib/tag-schema";

function jdContactRows(count = 7): TagSchemaField[] {
  return Array.from({ length: count }, (_, index) => {
    const rowIndex = index + 1;
    return {
      key: `jd_row_${rowIndex}`,
      label: `Job development contact ${rowIndex}`,
      type: "jd_contact_row",
      section: "Record of Job Development Contacts",
      rowIndex,
      dateKey: `rdate${rowIndex}`,
      initialKey: `initial${rowIndex}`,
      businessKey: `business${rowIndex}`,
      contactKey: `contact${rowIndex}`,
      resultsKey: `results${rowIndex}`,
    };
  });
}

/** Paste into admin → Tennessee VR Programs → IPS Monthly Progress Report → Tag schema (JSON). */
export const IPS_MONTHLY_PROGRESS_TAG_SCHEMA: TagSchemaField[] = [
  {
    key: "clientName",
    label: "Customer Name",
    type: "text",
    section: "Report header",
    prefill: "clientName",
    required: true,
  },
  {
    key: "reportMonth",
    label: "Report Month",
    type: "month",
    section: "Report header",
    required: true,
  },
  {
    key: "counselorName",
    label: "VR Counselor Name",
    type: "text",
    section: "Report header",
    prefill: "counselorName",
    required: true,
  },
  {
    key: "service1check",
    label: "Career Development & Placement",
    type: "boolean",
    section: "Service information",
    placeholder: "Check if this phase applies this month",
  },
  {
    key: "s1start",
    label: "Career Development & Placement — Start Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "s1complete",
    label: "Career Development & Placement — Completion Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "service2check",
    label: "Job Stabilization",
    type: "boolean",
    section: "Service information",
    placeholder: "Check if this phase applies this month",
  },
  {
    key: "s2start",
    label: "Job Stabilization — Start Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "s2complete",
    label: "Job Stabilization — Completion Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "service3check",
    label: "30 Day Stabilization & Maintenance",
    type: "boolean",
    section: "Service information",
    placeholder: "Check if this phase applies this month",
  },
  {
    key: "s3start",
    label: "30 Day Stabilization & Maintenance — Start Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "s3complete",
    label: "30 Day Stabilization & Maintenance — Completion Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "service4check",
    label: "60 Day Stabilization & Maintenance",
    type: "boolean",
    section: "Service information",
    placeholder: "Check if this phase applies this month",
  },
  {
    key: "s4start",
    label: "60 Day Stabilization & Maintenance — Start Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "s4complete",
    label: "60 Day Stabilization & Maintenance — Completion Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "service5check",
    label: "90 Day Stabilization & Maintenance",
    type: "boolean",
    section: "Service information",
    placeholder: "Check if this phase applies this month",
  },
  {
    key: "s5complete",
    label: "90 Day Stabilization & Maintenance — Completion Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "service6check",
    label: "Re-Engaging with Individual",
    type: "boolean",
    section: "Service information",
    placeholder: "Check if this phase applies this month",
  },
  {
    key: "s6start",
    label: "Re-Engaging with Individual — Start Date",
    type: "date",
    section: "Service information",
  },
  {
    key: "s6complete",
    label: "Re-Engaging with Individual — Completion Date",
    type: "date",
    section: "Service information",
    help: "Should coincide with start date of another phase when applicable.",
  },
  {
    key: "barriers",
    label: "Progress, services, barriers, and issues",
    type: "textarea",
    section: "Monthly narrative",
    help: "Identify and explain progress, services, barriers addressed and/or ongoing issues to resolve.",
    required: true,
  },
  {
    key: "jdcontactcheck",
    label: "Job Development Contact(s) Attached",
    type: "boolean",
    section: "Attachments",
    placeholder: "Check if job development contacts are attached",
  },
  {
    key: "hrcontactcheck",
    label: "Hire Report Attached",
    type: "boolean",
    section: "Attachments",
    placeholder: "Check if hire report is attached",
  },
  {
    key: "othercheck",
    label: "Other attachment",
    type: "boolean",
    section: "Attachments",
    placeholder: "Check if other attachment applies",
  },
  {
    key: "otherattached",
    label: "Other attachment description",
    type: "text",
    section: "Attachments",
    placeholder: "Describe other attachment if checked",
  },
  {
    key: "esName",
    label: "Employment Specialist Name",
    type: "text",
    section: "Certification",
    prefill: "esName",
    required: true,
  },
  {
    key: "date",
    label: "Certification Date",
    type: "date",
    section: "Certification",
    required: true,
  },
  {
    key: "jobspecifications",
    label: "Job Specifications (needs, preferences)",
    type: "textarea",
    section: "Job search planning",
  },
  {
    key: "jobsearchideas",
    label: "Job Search Ideas",
    type: "textarea",
    section: "Job search planning",
  },
  ...jdContactRows(7),
  {
    key: "continuation",
    label: "Continuation Page",
    type: "textarea",
    section: "Continuation",
    help: "Use for additional job development contacts or narrative if needed.",
  },
];
