import type { ClientActivityFeedItem } from "@wayfinder/branding";

export const DEMO_COUNSELOR = {
  full_name: "Pat Morgan",
  agency: "Georgia Vocational Rehabilitation Agency",
  emailHint: "official GVRA email",
};

/** Demo activity window: two calendar months (July–August 2026). */
export const DEMO_ACTIVITY_SPAN = {
  start: "2026-07-01",
  end: "2026-08-31",
} as const;

export type DemoCounselorClient = {
  linkId: string;
  displayName: string;
  serviceName: string;
  stage: string;
  applications: number;
  lastActivity: string;
  latestAppStatus: string | null;
  archived: boolean;
  esName: string;
};

/** Ordered by last name for counselor caseload (grid also sorts A–Z by last name). */
export const DEMO_COUNSELOR_CLIENTS: DemoCounselorClient[] = [
  {
    linkId: "sample-riley-brooks",
    displayName: "Riley Brooks",
    serviceName: "Workplace Readiness Training",
    stage: "Open",
    applications: 0,
    lastActivity: "2026-08-28T16:00:00.000Z",
    latestAppStatus: null,
    archived: false,
    esName: "Sam Rivera",
  },
  {
    linkId: "sample-morgan-ellis",
    displayName: "Morgan Ellis",
    serviceName: "Traditional Supported Employment",
    stage: "Job Development",
    applications: 4,
    lastActivity: "2026-08-27T15:20:00.000Z",
    latestAppStatus: "Interview scheduled",
    archived: false,
    esName: "Avery Quinn",
  },
  {
    linkId: "sample-casey-nguyen",
    displayName: "Casey Nguyen",
    serviceName: "Individual Job Placement (IJP)",
    stage: "Working",
    applications: 5,
    lastActivity: "2026-08-26T14:00:00.000Z",
    latestAppStatus: "Hired",
    archived: false,
    esName: "Jordan Blake",
  },
  {
    linkId: "sample-jamie-ortiz",
    displayName: "Jamie Ortiz",
    serviceName: "Job Coaching",
    stage: "Open",
    applications: 1,
    lastActivity: "2026-08-27T17:15:00.000Z",
    latestAppStatus: null,
    archived: false,
    esName: "Taylor Brooks",
  },
  {
    linkId: "sample-alex-reed",
    displayName: "Alex Reed",
    serviceName: "Traditional Supported Employment",
    stage: "Closed",
    applications: 2,
    lastActivity: "2026-08-22T11:00:00.000Z",
    latestAppStatus: null,
    archived: true,
    esName: "Avery Quinn",
  },
];

/**
 * ~6–7 activity items per month (July & August), with two in-person meetings
 * about two weeks apart (Aug 5 and Aug 19) for each client.
 * Meeting `at` matches `starts_at` so the timeline shows them on the meeting day.
 */
export const DEMO_COUNSELOR_FEEDS: Record<string, ClientActivityFeedItem[]> = {
  "sample-morgan-ellis": [
    {
      kind: "milestone",
      id: "m-me-1",
      at: "2026-07-02T14:00:00.000Z",
      title: "Job Development",
    },
    {
      kind: "contact",
      id: "c-me-1",
      at: "2026-07-07T15:30:00.000Z",
      public_outcome: "Phone call",
      notes: "Discussed target employers and transportation options for downtown shifts.",
    },
    {
      kind: "application",
      id: "a-me-1",
      at: "2026-07-10T18:00:00.000Z",
      status: "Applied",
      company_name: "Coastal Retail Group",
      notes: "Submitted online application with resume.",
    },
    {
      kind: "contact",
      id: "c-me-2",
      at: "2026-07-14T16:00:00.000Z",
      public_outcome: "Email",
      notes: "Sent interview prep checklist and sample answers for retail roles.",
    },
    {
      kind: "application",
      id: "a-me-2",
      at: "2026-07-17T17:20:00.000Z",
      status: "Applied",
      company_name: "Southside Grocery",
      notes: "In-store application completed with ES present.",
    },
    {
      kind: "contact",
      id: "c-me-3",
      at: "2026-07-22T14:45:00.000Z",
      public_outcome: "Phone call",
      notes: "Follow-up after Coastal Retail screen; waiting on next steps.",
    },
    {
      kind: "contact",
      id: "c-me-4",
      at: "2026-07-29T15:10:00.000Z",
      public_outcome: "Text message",
      notes: "Confirmed availability for early August employer outreach.",
    },
    {
      kind: "meeting",
      id: "mtg-me-1",
      at: "2026-08-05T18:00:00.000Z",
      status: "accepted",
      starts_at: "2026-08-05T18:00:00.000Z",
      location: "Savannah office · Room B",
      timezone: "America/New_York",
      service_name: "Traditional Supported Employment",
      es_name: "Avery Quinn",
    },
    {
      kind: "contact",
      id: "c-me-5",
      at: "2026-08-05T19:15:00.000Z",
      public_outcome: "Met in person at office",
      notes: "In-person meeting: practiced interview answers and reviewed Harbor Foods posting.",
    },
    {
      kind: "application",
      id: "a-me-3",
      at: "2026-08-08T16:40:00.000Z",
      status: "Applied",
      company_name: "Harbor Foods",
      notes: "Online application submitted after office session.",
    },
    {
      kind: "contact",
      id: "c-me-6",
      at: "2026-08-12T14:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Harbor Foods requested phone screen; coached on availability.",
    },
    {
      kind: "meeting",
      id: "mtg-me-2",
      at: "2026-08-19T18:00:00.000Z",
      status: "accepted",
      starts_at: "2026-08-19T18:00:00.000Z",
      location: "Savannah office · Room B",
      timezone: "America/New_York",
      service_name: "Traditional Supported Employment",
      es_name: "Avery Quinn",
    },
    {
      kind: "contact",
      id: "c-me-7",
      at: "2026-08-19T19:20:00.000Z",
      public_outcome: "Met in person at office",
      notes: "Second in-person meeting (~2 weeks later): mock interview and wardrobe check.",
    },
    {
      kind: "application",
      id: "a-me-4",
      at: "2026-08-27T15:20:00.000Z",
      status: "Interview scheduled",
      company_name: "Harbor Foods",
      notes: "In-person interview set for next week at the store.",
    },
  ],

  "sample-casey-nguyen": [
    {
      kind: "contact",
      id: "c-cn-1",
      at: "2026-07-01T15:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Reviewed open warehouse roles and lifting restrictions with ES.",
    },
    {
      kind: "application",
      id: "a-cn-1",
      at: "2026-07-03T17:00:00.000Z",
      status: "Applied",
      company_name: "Lowcountry Logistics",
      notes: "Submitted application for warehouse associate.",
    },
    {
      kind: "contact",
      id: "c-cn-2",
      at: "2026-07-08T14:30:00.000Z",
      public_outcome: "Email",
      notes: "Forwarded orientation packet and drug-screen instructions.",
    },
    {
      kind: "application",
      id: "a-cn-2",
      at: "2026-07-11T16:00:00.000Z",
      status: "Interview scheduled",
      company_name: "Lowcountry Logistics",
      notes: "On-site interview scheduled with shift supervisor.",
    },
    {
      kind: "contact",
      id: "c-cn-3",
      at: "2026-07-16T18:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Debrief after interview; employer positive on attendance reliability.",
    },
    {
      kind: "application",
      id: "a-cn-3",
      at: "2026-07-21T15:45:00.000Z",
      status: "Hired",
      company_name: "Lowcountry Logistics",
      notes: "Offer accepted — 32 hrs/week, start next month.",
    },
    {
      kind: "milestone",
      id: "m-cn-1",
      at: "2026-07-21T16:00:00.000Z",
      title: "Hired",
    },
    {
      kind: "meeting",
      id: "mtg-cn-1",
      at: "2026-08-05T17:00:00.000Z",
      status: "accepted",
      starts_at: "2026-08-05T17:00:00.000Z",
      location: "Lowcountry Logistics · break room",
      timezone: "America/New_York",
      service_name: "Individual Job Placement (IJP)",
      es_name: "Jordan Blake",
    },
    {
      kind: "contact",
      id: "c-cn-4",
      at: "2026-08-05T18:30:00.000Z",
      public_outcome: "Worksites visit",
      notes: "In-person meeting on site: first-week check-in with supervisor and ES.",
    },
    {
      kind: "milestone",
      id: "m-cn-2",
      at: "2026-08-06T14:00:00.000Z",
      title: "Working",
    },
    {
      kind: "contact",
      id: "c-cn-5",
      at: "2026-08-12T15:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Hours and uniform questions resolved with employer.",
    },
    {
      kind: "meeting",
      id: "mtg-cn-2",
      at: "2026-08-19T17:00:00.000Z",
      status: "accepted",
      starts_at: "2026-08-19T17:00:00.000Z",
      location: "Lowcountry Logistics · break room",
      timezone: "America/New_York",
      service_name: "Individual Job Placement (IJP)",
      es_name: "Jordan Blake",
    },
    {
      kind: "contact",
      id: "c-cn-6",
      at: "2026-08-19T18:20:00.000Z",
      public_outcome: "Worksites visit",
      notes: "Second in-person meeting (~2 weeks later): task pacing and break schedule.",
    },
    {
      kind: "contact",
      id: "c-cn-7",
      at: "2026-08-26T14:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Supervisor reports strong attendance; next check-in in two weeks.",
    },
  ],

  "sample-riley-brooks": [
    {
      kind: "milestone",
      id: "m-rb-1",
      at: "2026-07-01T14:00:00.000Z",
      title: "Open",
    },
    {
      kind: "contact",
      id: "c-rb-1",
      at: "2026-07-06T15:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Introduced Workplace Readiness Training calendar and attendance rules.",
    },
    {
      kind: "contact",
      id: "c-rb-2",
      at: "2026-07-10T16:30:00.000Z",
      public_outcome: "Email",
      notes: "Sent module syllabus and supply list for first week.",
    },
    {
      kind: "contact",
      id: "c-rb-3",
      at: "2026-07-15T14:00:00.000Z",
      public_outcome: "Group session",
      notes: "Completed soft-skills module on workplace communication.",
    },
    {
      kind: "contact",
      id: "c-rb-4",
      at: "2026-07-22T15:30:00.000Z",
      public_outcome: "Phone call",
      notes: "Parent/support check-in on transportation to training site.",
    },
    {
      kind: "contact",
      id: "c-rb-5",
      at: "2026-07-29T16:00:00.000Z",
      public_outcome: "Group session",
      notes: "Resume basics module; drafted personal strengths list.",
    },
    {
      kind: "meeting",
      id: "mtg-rb-1",
      at: "2026-08-05T19:00:00.000Z",
      status: "accepted",
      starts_at: "2026-08-05T19:00:00.000Z",
      location: "Career center · Training room 2",
      timezone: "America/New_York",
      service_name: "Workplace Readiness Training",
      es_name: "Sam Rivera",
    },
    {
      kind: "contact",
      id: "c-rb-6",
      at: "2026-08-05T20:15:00.000Z",
      public_outcome: "Met in person at school",
      notes: "In-person meeting: reviewed progress and set goals for interview practice.",
    },
    {
      kind: "contact",
      id: "c-rb-7",
      at: "2026-08-11T15:00:00.000Z",
      public_outcome: "Group session",
      notes: "Mock interview rotation with classmates.",
    },
    {
      kind: "contact",
      id: "c-rb-8",
      at: "2026-08-14T14:30:00.000Z",
      public_outcome: "Email",
      notes: "Shared feedback from mock interviews and practice prompts.",
    },
    {
      kind: "meeting",
      id: "mtg-rb-2",
      at: "2026-08-19T19:00:00.000Z",
      status: "accepted",
      starts_at: "2026-08-19T19:00:00.000Z",
      location: "Career center · Training room 2",
      timezone: "America/New_York",
      service_name: "Workplace Readiness Training",
      es_name: "Sam Rivera",
    },
    {
      kind: "contact",
      id: "c-rb-9",
      at: "2026-08-19T20:10:00.000Z",
      public_outcome: "Met in person at school",
      notes: "Second in-person meeting (~2 weeks later): hygiene and punctuality expectations.",
    },
    {
      kind: "contact",
      id: "c-rb-10",
      at: "2026-08-28T16:00:00.000Z",
      public_outcome: "Group session",
      notes: "Job-seeking module; practiced filling sample applications.",
    },
  ],

  "sample-jamie-ortiz": [
    {
      kind: "milestone",
      id: "m-jo-1",
      at: "2026-07-02T13:00:00.000Z",
      title: "Open",
    },
    {
      kind: "application",
      id: "a-jo-1",
      at: "2026-07-03T14:00:00.000Z",
      status: "Working",
      company_name: "Pinecrest Hospitality",
      notes: "Front-desk associate — coaching focused on task pacing.",
    },
    {
      kind: "contact",
      id: "c-jo-1",
      at: "2026-07-08T16:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Discussed coaching schedule around current job hours.",
    },
    {
      kind: "contact",
      id: "c-jo-2",
      at: "2026-07-14T15:30:00.000Z",
      public_outcome: "Email",
      notes: "Sent customer greeting script for practice before next shift.",
    },
    {
      kind: "contact",
      id: "c-jo-3",
      at: "2026-07-17T18:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Employer noted slower check-in times; plan on-site coaching.",
    },
    {
      kind: "contact",
      id: "c-jo-4",
      at: "2026-07-23T14:45:00.000Z",
      public_outcome: "On-site coaching",
      notes: "Shadowed front desk for one hour; modeled greeting flow.",
    },
    {
      kind: "contact",
      id: "c-jo-5",
      at: "2026-07-30T15:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Mid-month progress check; confidence improving with guests.",
    },
    {
      kind: "meeting",
      id: "mtg-jo-1",
      at: "2026-08-05T16:30:00.000Z",
      status: "accepted",
      starts_at: "2026-08-05T16:30:00.000Z",
      location: "Pinecrest Hospitality · lobby",
      timezone: "America/New_York",
      service_name: "Job Coaching",
      es_name: "Taylor Brooks",
    },
    {
      kind: "contact",
      id: "c-jo-6",
      at: "2026-08-05T17:45:00.000Z",
      public_outcome: "On-site coaching",
      notes: "In-person meeting: practiced guest greetings with ES on the floor.",
    },
    {
      kind: "contact",
      id: "c-jo-7",
      at: "2026-08-11T14:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Supervisor feedback positive after coaching visit.",
    },
    {
      kind: "contact",
      id: "c-jo-8",
      at: "2026-08-14T15:20:00.000Z",
      public_outcome: "Email",
      notes: "Shared updated pacing checklist for busy check-in times.",
    },
    {
      kind: "meeting",
      id: "mtg-jo-2",
      at: "2026-08-19T16:30:00.000Z",
      status: "accepted",
      starts_at: "2026-08-19T16:30:00.000Z",
      location: "Pinecrest Hospitality · lobby",
      timezone: "America/New_York",
      service_name: "Job Coaching",
      es_name: "Taylor Brooks",
    },
    {
      kind: "contact",
      id: "c-jo-9",
      at: "2026-08-19T17:50:00.000Z",
      public_outcome: "On-site coaching",
      notes: "Second in-person meeting (~2 weeks later): handled a busy arrival period together.",
    },
    {
      kind: "contact",
      id: "c-jo-10",
      at: "2026-08-27T17:15:00.000Z",
      public_outcome: "Phone call",
      notes: "Confirmed fading plan; ES will check in again next month.",
    },
  ],

  "sample-alex-reed": [
    {
      kind: "contact",
      id: "c-ar-1",
      at: "2026-07-02T15:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Reviewed goals met and remaining documentation for case close.",
    },
    {
      kind: "contact",
      id: "c-ar-2",
      at: "2026-07-08T14:30:00.000Z",
      public_outcome: "Email",
      notes: "Sent draft closure summary for counselor review.",
    },
    {
      kind: "application",
      id: "a-ar-1",
      at: "2026-07-11T16:00:00.000Z",
      status: "Closed",
      company_name: "Prior placement — archived",
      notes: "Historical placement record attached to closing packet.",
    },
    {
      kind: "contact",
      id: "c-ar-3",
      at: "2026-07-16T15:45:00.000Z",
      public_outcome: "Phone call",
      notes: "Participant confirmed employment stability and no further coaching needs.",
    },
    {
      kind: "application",
      id: "a-ar-2",
      at: "2026-07-22T14:00:00.000Z",
      status: "Working",
      company_name: "Community employer (prior)",
      notes: "Final status note for archive — still employed at close.",
    },
    {
      kind: "contact",
      id: "c-ar-4",
      at: "2026-07-28T16:20:00.000Z",
      public_outcome: "Email",
      notes: "Scheduled final in-person meetings for August closure.",
    },
    {
      kind: "meeting",
      id: "mtg-ar-1",
      at: "2026-08-05T17:30:00.000Z",
      status: "accepted",
      starts_at: "2026-08-05T17:30:00.000Z",
      location: "Savannah office · Room A",
      timezone: "America/New_York",
      service_name: "Traditional Supported Employment",
      es_name: "Avery Quinn",
    },
    {
      kind: "contact",
      id: "c-ar-5",
      at: "2026-08-05T18:40:00.000Z",
      public_outcome: "Met in person at office",
      notes: "In-person meeting: reviewed outcomes and exit survey together.",
    },
    {
      kind: "contact",
      id: "c-ar-6",
      at: "2026-08-11T15:00:00.000Z",
      public_outcome: "Phone call",
      notes: "Confirmed forwarding address and counselor contacts after close.",
    },
    {
      kind: "meeting",
      id: "mtg-ar-2",
      at: "2026-08-19T17:30:00.000Z",
      status: "accepted",
      starts_at: "2026-08-19T17:30:00.000Z",
      location: "Savannah office · Room A",
      timezone: "America/New_York",
      service_name: "Traditional Supported Employment",
      es_name: "Avery Quinn",
    },
    {
      kind: "contact",
      id: "c-ar-7",
      at: "2026-08-19T18:35:00.000Z",
      public_outcome: "Met in person at office",
      notes: "Second in-person meeting (~2 weeks later): signed closure paperwork.",
    },
    {
      kind: "milestone",
      id: "m-ar-1",
      at: "2026-08-22T11:00:00.000Z",
      title: "Closed",
    },
    {
      kind: "contact",
      id: "c-ar-8",
      at: "2026-08-22T11:15:00.000Z",
      public_outcome: "Email",
      notes: "Closure confirmation emailed to counselor and participant.",
    },
  ],
};

export function getDemoClient(linkId: string) {
  return DEMO_COUNSELOR_CLIENTS.find((c) => c.linkId === linkId) ?? null;
}
